/** Auto-generated by generate-openmouse-brand-icons.mjs - do not edit. */
export const OPENMOUSE_LOGO_RASTER: Record<string, 'png' | 'ico'> = {
  glorious: 'png',
  ninjutso: 'png',
  atk: 'png',
  pulsar: 'png',
  teevolution: 'png',
  wallhack: 'png',
  lamzu: 'ico',
  fantech: 'png',
  keychron: 'png',
  wooting: 'png',
  vgn: 'png',
}
