/** Generated by scripts/fetch-openmouse-product-images.mjs. */
export const OPENMOUSE_PRODUCT_IMAGES: Record<string, string> = {}
export const OPENMOUSE_UPSTREAM_MODEL_IMAGES: Record<string, string> = {}

export function openMouseProductImagePath(brandSlug: string, slug?: string): string | undefined {
  return slug ? OPENMOUSE_PRODUCT_IMAGES[`${brandSlug}/${slug}`] : undefined
}

export function openMouseUpstreamModelImagePath(brandSlug: string, slug?: string): string | undefined {
  return slug ? OPENMOUSE_UPSTREAM_MODEL_IMAGES[`${brandSlug}/${slug}`] : undefined
}
